import * as ecstra from "../../lib/ecstra/dist";
import * as MyEngine from "../engine/index";

export enum AnimationClipNames {
    STAND_DOWN = 'stand_down', STAND_UP = 'stand_up', STAND_LEFT = 'stand_left', STAND_RIGHT = 'stand_right',
    WALK_DOWN = 'walk_down', WALK_UP = 'walk_up', WALK_LEFT = 'walk_left', WALK_RIGHT = 'walk_right'
}
export interface AnimationClip {name: AnimationClipNames, frames: number[]}

/**
 * All rendering necessary.
 */
export default class RenderableComponent extends ecstra.ComponentData {
    @ecstra.string('')
    spriteUrl!: string;

    /**
     * Generated by BabylonJS sprite manager at scene initialization.
     * Used to render entity and play animation clips.
     */
    @ecstra.ref(null)
    sprite!: MyEngine.Sprites.Sprite;

    /**
     * Animation clips.
     * Key: direction. Value: Array of starting frame index and ending frame index.
     */
    @ecstra.ref(undefined)
    animationClips?: {[key: string]: AnimationClip};

    /**
     * Current playing animation clips.
     */
    @ecstra.ref()
    playingAnimationClip?: AnimationClip;

    /**
     * Delay time between frames by ms.
     */
    @ecstra.number(200)
    animationFrameDelay!: number;
}
